### PR TITLE
Added account support

### PR DESCRIPTION
**Pull request by TheRedSpy15**
Never tested, but any errors should be caught by an IDE. Should work, unless I made a super simple mistake

### CODE REVIEW

**Comment by RandomAdversary** [comment]
Thank you for the pull request.
I will look into it this weekend, and merge if everything is okay.

**Comment by TheRedSpy15** [comment]
I just put pasted the PwnedPasswords class into my IDE, managed to fix an error. I didn't run it though, was working on another project and thought I would go over it real quick

**Comment by TheRedSpy15** [comment]
@RandomAdversary It's been awhile, any progress on merging? would love to incorporate this feature into one of my projects

**Comment by RandomAdversary** [comment]
The changes were reverted because the code didn't work. Upon closer inspection, I noticed that the code doesn't match the api specs from: https://haveibeenpwned.com/API/v2#BreachesForAccount

**Comment by TheRedSpy15** [comment]
Ok, I have been testing this for 2 hours now, I keep getting a 403 response code, and yet the user agent is specified. Any ideas? @RandomAdversary

**Comment by RandomAdversary** [comment]
See the api specs from https://haveibeenpwned.com/API/v2#BreachesForAccount and compare to the code. You will see that, the code doesn't match the api specs.

**Pull request merged**
